[project]
name = "all-ai-tutorials"
version = "0.1.0"
description = "All my AI related tutorials for different libraries like pytorch, scikit learn and others"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
